from pathlib import Path
path = Path('/home/ubuntu/linhfarm/client/src/pages/Home.tsx')
text = path.read_text()
head = text.split('function Inventory(', 1)[0]
replacement = r'''function Inventory({ products, onAdd, onEdit, onDelete, onMenu, productMenu }: { products: Product[]; onAdd: () => void; onEdit: (product: Product) => void; onDelete: (id: number) => void; onMenu: (id: number | null) => void; productMenu: number | null }) {
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState("Tất cả");
  const filtered = products.filter(p => (category === "Tất cả" || p.category === category) && p.name.toLowerCase().includes(query.toLowerCase()));
  return <section className="page-section"><div className="section-heading"><div><span className="eyebrow">Danh mục & tồn kho</span><h2>Kho hàng</h2></div><button className="primary-button" onClick={onAdd}><Plus size={17} /> Thêm sản phẩm</button></div><div className="inventory-summary"><div><b>{products.length}</b><span>Tổng mặt hàng</span></div><div><b className="green-text">{products.filter(p => p.status === "Tươi mới").length}</b><span>Đang bán tốt</span></div><div><b className="orange-text">{products.filter(p => p.status === "Cần bán gấp").length}</b><span>Cần bán gấp</span></div><div><b className="red-text">{products.filter(p => p.status === "Hết hàng").length}</b><span>Hết hàng</span></div></div><div className="inventory-toolbar"><div className="search-box"><Search size={17} /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Tìm trong kho..." /></div><div className="category-tabs inventory-filters">{["Tất cả", "Trái cây", "Rau củ", "Đồ khô"].map(c => <button className={category === c ? "tab-active" : ""} onClick={() => setCategory(c)} key={c}>{c}</button>)}</div></div><div className="inventory-table">{filtered.map(p => <div className="inventory-row" key={p.id}><img src={p.image} /><div className="inventory-name"><strong>{p.name}</strong><span>{p.category} · Giá nhập {formatMoney(p.cost)}</span></div><div className="stock-cell"><b className={p.stock === 0 ? "red-text" : p.stock < 5 ? "orange-text" : ""}>{p.stock} {p.unit}</b><span>tồn kho</span></div><Badge tone={p.status === "Cần bán gấp" ? "orange" : p.status === "Hết hàng" ? "red" : "green"}>{p.status}</Badge><div className="row-actions"><button className="icon-button" onClick={() => onMenu(productMenu === p.id ? null : p.id)}><MoreHorizontal size={18} /></button>{productMenu === p.id && <div className="action-menu"><button onClick={() => { onEdit(p); onMenu(null); }}><FileText size={14} /> Chỉnh sửa thông tin</button><button className="danger-action" onClick={() => { onDelete(p.id); onMenu(null); }}><Trash2 size={14} /> Xóa sản phẩm</button></div>}</div></div>)}</div></section>;
}

function ProductModal({ mode, product, onClose, onSave }: { mode: "add" | "edit"; product?: Product; onClose: () => void; onSave: (product: Product) => void }) {
  const [form, setForm] = useState<Product>(product || { id: 0, name: "", category: "Trái cây", price: 0, cost: 0, stock: 0, unit: "Kg", status: "Tươi mới", image: assets.strawberry, accent: "#FBE7E4" });
  const update = (key: keyof Product, value: string | number) => setForm(current => ({ ...current, [key]: value }));
  const submit = (e: React.FormEvent) => { e.preventDefault(); if (!form.name.trim() || form.price <= 0 || form.cost < 0) return toast.error("Vui lòng nhập tên và giá hợp lệ"); onSave({ ...form, stock: Number(form.stock), price: Number(form.price), cost: Number(form.cost), status: Number(form.stock) === 0 ? "Hết hàng" : Number(form.stock) < 5 ? "Cần bán gấp" : "Tươi mới" }); };
  return <div className="modal-overlay"><form className="form-modal" onSubmit={submit}><div className="modal-head"><div><span className="eyebrow">Kho hàng</span><h2>{mode === "add" ? "Thêm sản phẩm" : "Chỉnh sửa sản phẩm"}</h2></div><button type="button" className="icon-button" onClick={onClose}><X size={19} /></button></div><div className="form-grid"><label>Tên sản phẩm<input required value={form.name} onChange={e => update("name", e.target.value)} placeholder="Ví dụ: Dâu tây Giống Nhật" /></label><label>Danh mục<select value={form.category} onChange={e => update("category", e.target.value)}><option>Trái cây</option><option>Rau củ</option><option>Đồ khô</option></select></label><label>Giá nhập<input type="number" min="0" value={form.cost} onChange={e => update("cost", Number(e.target.value))} /></label><label>Giá bán<input required type="number" min="1" value={form.price} onChange={e => update("price", Number(e.target.value))} /></label><label>Đơn vị tính<select value={form.unit} onChange={e => update("unit", e.target.value)}><option>Kg</option><option>Gram</option><option>Hộp</option><option>Túi</option><option>Khay</option></select></label><label>Tồn kho ban đầu<input type="number" min="0" step="0.1" value={form.stock} onChange={e => update("stock", Number(e.target.value))} /></label><label className="full-field">URL ảnh<input value={form.image} onChange={e => update("image", e.target.value)} placeholder="https://... hoặc đường dẫn ảnh" /></label></div><div className="modal-actions"><button type="button" className="outline-button" onClick={onClose}>Hủy</button><button type="submit" className="primary-button"><Check size={16} /> Lưu sản phẩm</button></div></form></div>;
}

function Suppliers({ products, onAdd, onImport }: { products: Product[]; onAdd: () => void; onImport: (items: { productId: number; qty: number; unitCost: number }[]) => void }) {
  return <section className="page-section"><div className="section-heading"><div><span className="eyebrow">Nguồn hàng Đà Lạt</span><h2>Nhập hàng</h2></div><button className="primary-button" onClick={onAdd}><Plus size={17} /> Tạo phiếu nhập</button></div><div className="supplier-hero"><div><span className="eyebrow">Chi phí nhập tháng 8</span><strong>18,4 triệu <small>VNĐ</small></strong><p>12 phiếu nhập · 4 nhà cung cấp</p></div><div className="supplier-sprout"><Leaf size={34} /></div></div><div className="supplier-list"><h3>Nhà cung cấp gần đây</h3>{[{ name: "Nông trại Dâu Nhật Hưng Phát", meta: "Dâu tây · Nhập 12/08", amount: "4.250.000đ", tag: "Đã nhận" }, { name: "HTX Rau sạch Cầu Đất", meta: "Rau củ · Nhập 11/08", amount: "2.860.000đ", tag: "Đã nhận" }, { name: "Vựa đặc sản Minh Tâm", meta: "Đồ khô · Nhập 09/08", amount: "1.680.000đ", tag: "Đã nhận" }].map(s => <div className="supplier-row" key={s.name}><div className="supplier-avatar"><Truck size={18} /></div><div><strong>{s.name}</strong><span>{s.meta}</span></div><div className="supplier-amount"><b>{s.amount}</b><Badge>{s.tag}</Badge></div></div>)}</div></section>;
}

function SupplierModal({ products, onClose, onSave }: { products: Product[]; onClose: () => void; onSave: (items: { productId: number; qty: number; unitCost: number }[]) => void }) {
  const [supplier, setSupplier] = useState("Nông trại Dâu Nhật Hưng Phát");
  const [lines, setLines] = useState([{ productId: products[0]?.id || 0, qty: 1, unitCost: products[0]?.cost || 0 }]);
  const total = lines.reduce((sum, line) => sum + line.qty * line.unitCost, 0);
  const updateLine = (index: number, key: "productId" | "qty" | "unitCost", value: number) => setLines(current => current.map((line, i) => i === index ? { ...line, [key]: value } : line));
  return <div className="modal-overlay"><div className="form-modal"><div className="modal-head"><div><span className="eyebrow">Phiếu nhập hàng</span><h2>Nhập từ Đà Lạt</h2></div><button className="icon-button" onClick={onClose}><X size={19} /></button></div><label>Nhà cung cấp<select value={supplier} onChange={e => setSupplier(e.target.value)}><option>Nông trại Dâu Nhật Hưng Phát</option><option>HTX Rau sạch Cầu Đất</option><option>Vựa đặc sản Minh Tâm</option></select></label><div className="import-lines">{lines.map((line, index) => <div className="import-line" key={index}><select value={line.productId} onChange={e => updateLine(index, "productId", Number(e.target.value))}>{products.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select><input type="number" min="0.1" step="0.1" value={line.qty} onChange={e => updateLine(index, "qty", Number(e.target.value))} placeholder="SL" /><input type="number" min="0" value={line.unitCost} onChange={e => updateLine(index, "unitCost", Number(e.target.value))} placeholder="Đơn giá" />{lines.length > 1 && <button className="icon-button" onClick={() => setLines(current => current.filter((_, i) => i !== index))}><Trash2 size={14} /></button>}</div>)}</div><button className="text-button" onClick={() => setLines(current => [...current, { productId: products[0]?.id || 0, qty: 1, unitCost: products[0]?.cost || 0 }])}><Plus size={14} /> Thêm sản phẩm nhập</button><div className="import-total"><span>Tổng tiền nhập</span><strong>{formatMoney(total)}</strong></div><div className="modal-actions"><button className="outline-button" onClick={onClose}>Hủy</button><button className="primary-button" onClick={() => lines.length && onSave(lines)}><Check size={16} /> Hoàn tất phiếu nhập</button></div></div></div>;
}

function SettingsPage({ storeInfo, onEdit }: { storeInfo: { address: string; phone: string; bank: string; account: string; accountName: string }; onEdit: (kind: "shop" | "invoice" | "payment") => void }) {
  return <section className="page-section settings-page"><div className="section-heading"><div><span className="eyebrow">Vận hành cửa hàng</span><h2>Cài đặt</h2></div></div><div className="settings-card shop-profile-card"><div className="big-logo"><img src={assets.logo} /></div><div><h3>LinhFarm · Đà Lạt</h3><p>{storeInfo.address}</p><span>Đang hoạt động · {storeInfo.phone}</span></div><button className="outline-button" onClick={() => onEdit("shop")}>Chỉnh sửa</button></div><div className="settings-list">{[{ icon: FileText, title: "Thông tin hóa đơn", detail: `${storeInfo.address} · ${storeInfo.phone}`, kind: "invoice" as const }, { icon: CreditCard, title: "Thanh toán & VietQR", detail: `${storeInfo.bank} · ${storeInfo.accountName} · ${storeInfo.account}`, kind: "payment" as const }, { icon: Bell, title: "Thông báo tồn kho", detail: "Cảnh báo khi sản phẩm dưới mức tối thiểu" }, { icon: Settings, title: "Giao diện & thiết bị", detail: "Máy in nhiệt · 80mm · Tiếng Việt" }].map(x => <button className="settings-row" key={x.title} onClick={() => x.kind && onEdit(x.kind)}><span className="settings-icon"><x.icon size={18} /></span><span><strong>{x.title}</strong><small>{x.detail}</small></span><ArrowUpRight size={17} /></button>)}</div></section>;
}

function SettingsModal({ kind, info, onClose, onSave }: { kind: "shop" | "invoice" | "payment"; info: { address: string; phone: string; bank: string; account: string; accountName: string }; onClose: () => void; onSave: (info: typeof info) => void }) {
  const [form, setForm] = useState(info);
  const update = (key: keyof typeof info, value: string) => setForm(current => ({ ...current, [key]: value }));
  const title = kind === "payment" ? "Thanh toán & VietQR" : kind === "invoice" ? "Thông tin hóa đơn" : "Thông tin cửa hàng";
  return <div className="modal-overlay"><form className="form-modal" onSubmit={e => { e.preventDefault(); onSave(form); }}><div className="modal-head"><div><span className="eyebrow">Cài đặt LinhFarm</span><h2>{title}</h2></div><button type="button" className="icon-button" onClick={onClose}><X size={19} /></button></div><div className="form-grid">{kind !== "payment" && <><label>Địa chỉ cửa hàng<textarea rows={2} value={form.address} onChange={e => update("address", e.target.value)} /></label><label>Số điện thoại<input value={form.phone} onChange={e => update("phone", e.target.value)} /></label></>}{kind === "payment" && <><label>Ngân hàng<input value={form.bank} onChange={e => update("bank", e.target.value)} /></label><label>Số tài khoản<input value={form.account} onChange={e => update("account", e.target.value)} /></label><label className="full-field">Tên chủ tài khoản<input value={form.accountName} onChange={e => update("accountName", e.target.value)} /></label></>}{kind === "invoice" && <label>Khổ giấy<select defaultValue="80mm"><option>58mm</option><option>80mm</option></select></label>}</div><div className="modal-actions"><button type="button" className="outline-button" onClick={onClose}>Hủy</button><button type="submit" className="primary-button"><Check size={16} /> Lưu cài đặt</button></div></form></div>;
}

function BillModal({ total, cart, payment, onClose }: any) { return <div className="modal-overlay"><div className="bill-modal"><div className="modal-head"><div><span className="eyebrow">Đơn hàng đã tạo</span><h2>Hóa đơn xem trước</h2></div><button className="icon-button" onClick={onClose}><X size={19} /></button></div><div className="thermal-bill" id="thermal-bill"><div className="bill-brand"><img src={assets.logo} /><strong>LinhFarm</strong><span>Đặc sản tươi Đà Lạt</span></div><div className="bill-meta">Mã đơn: <b>LF-1308-043</b><br />13/08/2026 · 11:06 · {payment}</div><div className="bill-items">{cart.map((x: CartItem) => <div key={x.id}><span>{x.name}<small>{x.qty} {x.selectedUnit} × {formatMoney(x.price)}</small></span><b>{formatMoney(x.qty * x.price)}</b></div>)}</div><div className="bill-total"><span>TỔNG CỘNG</span><strong>{formatMoney(total)}</strong></div><div className="bill-footer">Cảm ơn bạn đã ủng hộ nông sản Đà Lạt.<br />18 Nguyễn Văn Trỗi · 0263 382 6868</div></div><div className="bill-actions"><button className="outline-button" onClick={() => { navigator.clipboard?.writeText(`LinhFarm - Đơn LF-1308-043
Tổng: ${formatMoney(total)}`); toast.success("Đã copy nội dung bill"); }}><Copy size={16} /> Copy gửi Zalo</button><button className="primary-button" onClick={() => window.print()}><Printer size={16} /> In hóa đơn</button></div></div></div> }
'''
path.write_text(head + replacement)
