from pathlib import Path
p = Path('/home/ubuntu/linhfarm/client/src/pages/Home.tsx')
s = p.read_text()
head = s.split('function ProductModal(', 1)[0]
tail = s.split('function Suppliers(', 1)[1]
modal = r'''function ProductModal({ mode, product, onClose, onSave }: { mode: "add" | "edit"; product?: Product; onClose: () => void; onSave: (product: Product, imageFile?: File | null) => void }) {
  const [form, setForm] = useState<Product>(product || { id: 0, name: "", category: "Trái cây", price: 0, cost: 0, stock: 0, unit: "Kg", status: "Tươi mới", image: assets.strawberry, accent: "#FBE7E4" });
  const [imageFile, setImageFile] = useState<File | null>(null);
  const [previewUrl, setPreviewUrl] = useState(product?.image || assets.strawberry);
  const update = (key: keyof Product, value: string | number) => setForm(current => ({ ...current, [key]: value }));
  useEffect(() => { return () => { if (previewUrl.startsWith("blob:")) URL.revokeObjectURL(previewUrl); }; }, [previewUrl]);
  const pickImage = (file?: File) => { if (!file) return; if (!file.type.startsWith("image/")) return toast.error("Vui lòng chọn file hình ảnh"); if (file.size > 5 * 1024 * 1024) return toast.error("Ảnh không được vượt quá 5MB"); if (previewUrl.startsWith("blob:")) URL.revokeObjectURL(previewUrl); const nextUrl = URL.createObjectURL(file); setImageFile(file); setPreviewUrl(nextUrl); setForm(current => ({ ...current, image: nextUrl })); };
  const submit = (e: React.FormEvent) => { e.preventDefault(); if (!form.name.trim() || form.price <= 0 || form.cost < 0) return toast.error("Vui lòng nhập tên và giá hợp lệ"); onSave({ ...form, stock: Number(form.stock), price: Number(form.price), cost: Number(form.cost), status: Number(form.stock) === 0 ? "Hết hàng" : Number(form.stock) < 5 ? "Cần bán gấp" : "Tươi mới" }, imageFile); };
  return <div className="modal-overlay"><form className="form-modal" onSubmit={submit}><div className="modal-head"><div><span className="eyebrow">Kho hàng</span><h2>{mode === "add" ? "Thêm sản phẩm" : "Chỉnh sửa sản phẩm"}</h2></div><button type="button" className="icon-button" onClick={onClose}><X size={19} /></button></div><div className="form-grid"><label>Tên sản phẩm<input required value={form.name} onChange={e => update("name", e.target.value)} placeholder="Ví dụ: Dâu tây Giống Nhật" /></label><label>Danh mục<select value={form.category} onChange={e => update("category", e.target.value)}><option>Trái cây</option><option>Rau củ</option><option>Đồ khô</option></select></label><label>Giá nhập<input type="number" min="0" value={form.cost} onChange={e => update("cost", Number(e.target.value))} /></label><label>Giá bán<input required type="number" min="1" value={form.price} onChange={e => update("price", Number(e.target.value))} /></label><label>Đơn vị tính<select value={form.unit} onChange={e => update("unit", e.target.value)}><option>Kg</option><option>Gram</option><option>Hộp</option><option>Túi</option><option>Khay</option></select></label><label>Tồn kho ban đầu<input type="number" min="0" step="0.1" value={form.stock} onChange={e => update("stock", Number(e.target.value))} /></label><div className="image-upload-field full-field"><span>Ảnh sản phẩm</span><label className="image-dropzone" onDragOver={e => e.preventDefault()} onDrop={e => { e.preventDefault(); pickImage(e.dataTransfer.files[0]); }}><input type="file" accept="image/png,image/jpeg,image/webp" onChange={e => pickImage(e.target.files?.[0])} /><img src={previewUrl} alt="Xem trước sản phẩm" /><div><strong>{imageFile ? imageFile.name : "Chọn hoặc kéo thả ảnh vào đây"}</strong><small>PNG, JPG hoặc WEBP · tối đa 5MB</small></div><span className="upload-browse">Chọn ảnh</span></label></div></div><div className="modal-actions"><button type="button" className="outline-button" onClick={onClose}>Hủy</button><button type="submit" className="primary-button"><Check size={16} /> Lưu sản phẩm</button></div></form></div>;
}

function Suppliers('''
p.write_text(head + modal + tail)
