-- LinhFarm / Supabase schema
-- Chạy file này trong Supabase SQL Editor.
-- Các policy anon phục vụ bản demo hiện tại; khi bật Supabase Auth, hãy giới hạn ghi theo user/role.

create extension if not exists pgcrypto;

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null unique,
  category text not null check (category in ('Trái cây', 'Rau củ', 'Đồ khô')),
  unit text not null check (unit in ('Kg', 'Gram', 'Hộp', 'Túi', 'Khay')),
  cost_price numeric(12,2) not null default 0 check (cost_price >= 0),
  selling_price numeric(12,2) not null default 0 check (selling_price >= 0),
  stock numeric(12,3) not null default 0 check (stock >= 0),
  min_stock numeric(12,3) not null default 5 check (min_stock >= 0),
  status text not null default 'Tươi mới' check (status in ('Tươi mới', 'Cần bán gấp', 'Hết hàng')),
  image_url text,
  accent text default '#E6F3E9',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_code text not null unique,
  payment_method text not null check (payment_method in ('Tiền mặt', 'Chuyển khoản')),
  subtotal numeric(12,2) not null default 0,
  total_amount numeric(12,2) not null default 0,
  estimated_profit numeric(12,2) not null default 0,
  status text not null default 'completed' check (status in ('completed', 'cancelled')),
  created_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id bigint not null references public.products(id),
  product_name text not null,
  quantity numeric(12,3) not null check (quantity > 0),
  unit text not null,
  unit_price numeric(12,2) not null,
  unit_cost numeric(12,2) not null,
  line_total numeric(12,2) generated always as (quantity * unit_price) stored,
  created_at timestamptz not null default now()
);

create table if not exists public.suppliers (
  id bigint generated by default as identity primary key,
  name text not null unique,
  phone text,
  address text,
  note text,
  created_at timestamptz not null default now()
);

create table if not exists public.purchase_orders (
  id bigint generated by default as identity primary key,
  purchase_code text not null unique,
  supplier_id bigint references public.suppliers(id) on delete set null,
  supplier_name text not null,
  total_amount numeric(12,2) not null default 0,
  note text default '',
  status text not null default 'received' check (status in ('draft', 'received', 'cancelled')),
  received_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.purchase_order_items (
  id bigint generated by default as identity primary key,
  purchase_order_id bigint not null references public.purchase_orders(id) on delete cascade,
  product_id bigint not null references public.products(id),
  quantity numeric(12,3) not null check (quantity > 0),
  import_price numeric(12,2) not null check (import_price >= 0),
  total_price numeric(12,2) generated always as (quantity * import_price) stored,
  created_at timestamptz not null default now()
);

create table if not exists public.store_settings (
  id integer primary key default 1 check (id = 1),
  store_name text not null default 'LinhFarm',
  address text not null default '18 Nguyễn Văn Trỗi, Phường 2, TP. Đà Lạt',
  phone text not null default '0263 382 6868',
  bank_name text not null default 'MB Bank',
  bank_account text not null default '**** 8899',
  account_name text not null default 'LINH FARM',
  invoice_paper text not null default '80mm',
  updated_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists products_set_updated_at on public.products;
create trigger products_set_updated_at before update on public.products for each row execute function public.set_updated_at();
drop trigger if exists store_settings_set_updated_at on public.store_settings;
create trigger store_settings_set_updated_at before update on public.store_settings for each row execute function public.set_updated_at();

create or replace function public.create_order_with_items(
  p_payment_method text,
  p_items jsonb
) returns public.orders
language plpgsql security definer set search_path = public as $$
declare
  v_order public.orders;
  v_item jsonb;
  v_product public.products;
  v_total numeric(12,2) := 0;
  v_profit numeric(12,2) := 0;
  v_qty numeric(12,3);
begin
  for v_item in select * from jsonb_array_elements(p_items) loop
    select * into v_product from public.products where id = (v_item->>'product_id')::bigint for update;
    v_qty := (v_item->>'quantity')::numeric;
    if v_product.id is null then raise exception 'Product not found'; end if;
    if v_product.stock < v_qty then raise exception 'Insufficient stock for %', v_product.name; end if;
    v_total := v_total + v_qty * v_product.selling_price;
    v_profit := v_profit + v_qty * (v_product.selling_price - v_product.cost_price);
  end loop;

  insert into public.orders(order_code, payment_method, subtotal, total_amount, estimated_profit)
  values ('LF-' || to_char(now(), 'DDMM') || '-' || lpad(nextval('public.orders_id_seq')::text, 3, '0'), p_payment_method, v_total, v_total, v_profit)
  returning * into v_order;

  for v_item in select * from jsonb_array_elements(p_items) loop
    select * into v_product from public.products where id = (v_item->>'product_id')::bigint for update;
    v_qty := (v_item->>'quantity')::numeric;
    insert into public.order_items(order_id, product_id, product_name, quantity, unit, unit_price, unit_cost)
    values (v_order.id, v_product.id, v_product.name, v_qty, coalesce(v_item->>'unit', v_product.unit), v_product.selling_price, v_product.cost_price);
    update public.products set stock = stock - v_qty, status = case when stock - v_qty <= 0 then 'Hết hàng' when stock - v_qty <= min_stock then 'Cần bán gấp' else 'Tươi mới' end where id = v_product.id;
  end loop;
  return v_order;
end;
$$;

create or replace function public.create_purchase_order_with_items(
  p_supplier_name text,
  p_items jsonb,
  p_supplier_id bigint default null,
  p_note text default ''
) returns public.purchase_orders
language plpgsql security definer set search_path = public as $$
declare
  v_po public.purchase_orders;
  v_item jsonb;
  v_product public.products;
  v_total numeric(12,2) := 0;
  v_qty numeric(12,3);
  v_cost numeric(12,2);
  v_new_stock numeric(12,3);
begin
  for v_item in select * from jsonb_array_elements(p_items) loop
    v_qty := (v_item->>'qty')::numeric;
    v_cost := (v_item->>'unitCost')::numeric;
    v_total := v_total + (v_qty * v_cost);
  end loop;

  insert into public.purchase_orders(purchase_code, supplier_id, supplier_name, total_amount, note, status)
  values ('PO-' || to_char(now(), 'DDMM') || '-' || lpad(nextval('public.purchase_orders_id_seq')::text, 3, '0'), p_supplier_id, p_supplier_name, v_total, p_note, 'received')
  returning * into v_po;

  for v_item in select * from jsonb_array_elements(p_items) loop
    select * into v_product from public.products where id = (v_item->>'productId')::bigint for update;
    v_qty := (v_item->>'qty')::numeric;
    v_cost := (v_item->>'unitCost')::numeric;

    insert into public.purchase_order_items(purchase_order_id, product_id, quantity, import_price)
    values (v_po.id, v_product.id, v_qty, v_cost);

    v_new_stock := v_product.stock + v_qty;
    update public.products
    set stock = v_new_stock,
        cost_price = case when v_cost > 0 then v_cost else cost_price end,
        status = case
          when v_new_stock <= 0 then 'Hết hàng'
          when v_new_stock <= v_product.min_stock then 'Cần bán gấp'
          else 'Tươi mới'
        end
    where id = v_product.id;
  end loop;

  return v_po;
end;
$$;

alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.suppliers enable row level security;
alter table public.purchase_orders enable row level security;
alter table public.purchase_order_items enable row level security;
alter table public.store_settings enable row level security;

drop policy if exists products_public_access on public.products;
create policy products_public_access on public.products for all to anon, authenticated using (true) with check (true);
drop policy if exists orders_public_access on public.orders;
create policy orders_public_access on public.orders for all to anon, authenticated using (true) with check (true);
drop policy if exists order_items_public_access on public.order_items;
create policy order_items_public_access on public.order_items for all to anon, authenticated using (true) with check (true);
drop policy if exists suppliers_public_access on public.suppliers;
create policy suppliers_public_access on public.suppliers for all to anon, authenticated using (true) with check (true);
drop policy if exists purchase_orders_public_access on public.purchase_orders;
create policy purchase_orders_public_access on public.purchase_orders for all to anon, authenticated using (true) with check (true);
drop policy if exists purchase_order_items_public_access on public.purchase_order_items;
create policy purchase_order_items_public_access on public.purchase_order_items for all to anon, authenticated using (true) with check (true);
drop policy if exists store_settings_public_access on public.store_settings;
create policy store_settings_public_access on public.store_settings for all to anon, authenticated using (true) with check (true);

insert into public.suppliers (name, phone, address, note) values
('Nông trại Dâu Nhật Hưng Phát', '0901 234 567', 'Phường 11, TP. Đà Lạt', 'Chuyên dâu tây chất lượng cao'),
('HTX Rau sạch Cầu Đất', '0912 345 678', 'Xã Trạm Hành, TP. Đà Lạt', 'Rau củ hữu cơ chuẩn VietGAP'),
('Vựa đặc sản Minh Tâm', '0923 456 789', 'Phường 3, TP. Đà Lạt', 'Cung cấp đồ khô & hồng giòn')
on conflict (name) do nothing;

insert into public.store_settings(id) values (1) on conflict (id) do nothing;

insert into public.products (name, category, unit, cost_price, selling_price, stock, min_stock, status, image_url, accent) values
('Dâu tây Giống Nhật', 'Trái cây', 'Kg', 125000, 185000, 8.4, 5, 'Tươi mới', '/manus-storage/linhfarm-strawberry_2d520d42.jpg', '#FBE7E4'),
('Cà chua Cherry', 'Rau củ', 'Kg', 58000, 89000, 12.5, 10, 'Tươi mới', '/manus-storage/linhfarm-cherry-tomato_b162fddc.jpg', '#FFF1E2'),
('Bắp cải trái tim', 'Rau củ', 'Kg', 24000, 42000, 19, 5, 'Tươi mới', '/manus-storage/linhfarm-cabbage_84c4bca3.jpg', '#E6F3E9'),
('Khoai mật nướng', 'Đồ khô', 'Kg', 38000, 65000, 6.8, 8, 'Cần bán gấp', '/manus-storage/linhfarm-sweet-potato_7970a415.jpg', '#F7EBDD'),
('Hồng giòn Đà Lạt', 'Trái cây', 'Kg', 49000, 79000, 15.2, 5, 'Tươi mới', '/manus-storage/linhfarm-strawberry_2d520d42.jpg', '#FBE7E4'),
('Asparagus xanh', 'Rau củ', 'Kg', 84000, 125000, 3.2, 5, 'Cần bán gấp', '/manus-storage/linhfarm-cabbage_84c4bca3.jpg', '#E6F3E9'),
('Mứt dâu thủ công', 'Đồ khô', 'Hộp', 62000, 98000, 22, 5, 'Tươi mới', '/manus-storage/linhfarm-strawberry_2d520d42.jpg', '#FBE7E4'),
('Xà lách thủy canh', 'Rau củ', 'Túi', 32000, 55000, 0, 5, 'Hết hàng', '/manus-storage/linhfarm-cabbage_84c4bca3.jpg', '#E6F3E9')
on conflict (name) do update set stock = excluded.stock, updated_at = now();

insert into public.orders (order_code, payment_method, subtotal, total_amount, estimated_profit, created_at) values
('LF-1308-040', 'Tiền mặt', 158000, 158000, 60000, now() - interval '1 day'),
('LF-1308-041', 'Tiền mặt', 207000, 207000, 97000, now() - interval '12 hours'),
('LF-1308-042', 'Chuyển khoản', 368000, 368000, 120000, now() - interval '2 hours')
on conflict (order_code) do nothing;

-- Supabase Storage bucket for product images.
-- Public Read is intentional because products.image_url stores public URLs.
insert into storage.buckets (id, name, public)
values ('linhfarm-images', 'linhfarm-images', true)
on conflict (id) do update set public = true;

drop policy if exists linhfarm_images_public_read on storage.objects;
create policy linhfarm_images_public_read
on storage.objects for select
to anon, authenticated
using (bucket_id = 'linhfarm-images');

drop policy if exists linhfarm_images_public_upload on storage.objects;
create policy linhfarm_images_public_upload
on storage.objects for insert
to anon, authenticated
with check (bucket_id = 'linhfarm-images');

drop policy if exists linhfarm_images_public_update on storage.objects;
create policy linhfarm_images_public_update
on storage.objects for update
to anon, authenticated
using (bucket_id = 'linhfarm-images')
with check (bucket_id = 'linhfarm-images');

drop policy if exists linhfarm_images_public_delete on storage.objects;
create policy linhfarm_images_public_delete
on storage.objects for delete
to anon, authenticated
using (bucket_id = 'linhfarm-images');
